
version: '3.5'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dipren-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: YES
      MSSQL_SA_PASSWORD: 4Laqzjn!LNYa@W63
      MSSQL_PID: Developer
    ports:
      - "1433:1433"

networks:
  default:
    name: dipren_network
