//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Data.SqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlServerEngineDataStoreImplementationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlServerEngineDataStoreImplementationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Data.SqlServer.SqlServerEngineDataStoreImplementationResources", typeof(SqlServerEngineDataStoreImplementationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
        ///
        ///SELECT
        ///  (SELECT COUNT_BIG(1) FROM [dipren].[jobs] WHERE ([id] = @job_id)) AS [job_count],
        ///  (SELECT COUNT_BIG(1) FROM [dipren].[partitions] WHERE ([job_id] = @job_id) AND ([is_completed] = 0)) AS [partition_count];.
        /// </summary>
        internal static string QueryCountIncompletePartitions {
            get {
                return ResourceManager.GetString("QueryCountIncompletePartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
        ///
        ///SELECT
        ///  COUNT_BIG(1) AS [count]
        ///FROM
        ///  [dipren].[jobs];.
        /// </summary>
        internal static string QueryCountJobs {
            get {
                return ResourceManager.GetString("QueryCountJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
        ///
        ///SELECT
        ///  COUNT(1) AS [count]
        ///FROM
        ///  [dipren].[partitions]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryDoesPartitionExist {
            get {
                return ResourceManager.GetString("QueryDoesPartitionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dipren].[jobs]
        ///(
        ///  [id],
        ///  [created],
        ///  [updated],
        ///  [batch_size],
        ///  [timeout],
        ///  [clock_drift],
        ///  [started],
        ///  [completed],
        ///  [state],
        ///  [error]
        ///)
        ///VALUES
        ///(
        ///  @id,
        ///  @created,
        ///  @updated,
        ///  @batch_size,
        ///  @timeout,
        ///  @clock_drift,
        ///  @started,
        ///  @completed,
        ///  @state,
        ///  @error
        ///);.
        /// </summary>
        internal static string QueryInsertJob {
            get {
                return ResourceManager.GetString("QueryInsertJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///INSERT INTO [dipren].[partitions]
        ///(
        ///  [id],
        ///  [job_id],
        ///  [created],
        ///  [owner],
        ///  [first],
        ///  [last],
        ///  [is_inclusive],
        ///  [is_completed],
        ///  [split_requester]
        ///)
        ///VALUES
        ///(
        ///  @id,
        ///  @job_id,
        ///  @created,
        ///  @owner,
        ///  @first,
        ///  @last,
        ///  @is_inclusive,
        ///  @is_completed,
        ///  @split_requester
        ///);
        ///
        ///INSERT INTO [dipren].[progress]
        ///(
        ///  [id],
        ///  [updated],
        ///  [position],
        ///  [processed],
        ///  [remaining],
        ///  [throughput]
        ///)
        ///VALUES
        ///(
        ///  @id,
        ///  @updated,
        ///  @position,
        ///  @process [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryInsertPartition {
            get {
                return ResourceManager.GetString("QueryInsertPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SELECT
        ///  COALESCE((SELECT TOP (1) 1 FROM [dipren].[partitions] WHERE ([job_id] = @job_id) AND ([split_requester] = @requester)), 0) AS [requests_exist];.
        /// </summary>
        internal static string QueryIsSplitRequestPending {
            get {
                return ResourceManager.GetString("QueryIsSplitRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///  [dipren].[jobs]
        ///SET
        ///  [updated] = @timestamp,
        ///  [completed] = @timestamp,
        ///  [state] = @state
        ///OUTPUT
        ///  INSERTED.[id] AS [id],
        ///  INSERTED.[created] AS [created],
        ///  INSERTED.[updated] AS [updated],
        ///  INSERTED.[batch_size] AS [batch_size],
        ///  INSERTED.[timeout] AS [timeout],
        ///  INSERTED.[clock_drift] AS [clock_drift],
        ///  INSERTED.[started] AS [started],
        ///  INSERTED.[completed] AS [completed],
        ///  INSERTED.[state] AS [state],
        ///  INSERTED.[error] AS [error]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryMarkJobAsCompleted {
            get {
                return ResourceManager.GetString("QueryMarkJobAsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///  [dipren].[jobs]
        ///SET
        ///  [updated] = @timestamp,
        ///  [state] = @state,
        ///  [error] = @error
        ///OUTPUT
        ///  INSERTED.[id] AS [id],
        ///  INSERTED.[created] AS [created],
        ///  INSERTED.[updated] AS [updated],
        ///  INSERTED.[batch_size] AS [batch_size],
        ///  INSERTED.[timeout] AS [timeout],
        ///  INSERTED.[clock_drift] AS [clock_drift],
        ///  INSERTED.[started] AS [started],
        ///  INSERTED.[completed] AS [completed],
        ///  INSERTED.[state] AS [state],
        ///  INSERTED.[error] AS [error]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryMarkJobAsFailed {
            get {
                return ResourceManager.GetString("QueryMarkJobAsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///  [dipren].[jobs]
        ///SET
        ///  [updated] = @timestamp,
        ///  [state] = @state
        ///OUTPUT
        ///  INSERTED.[id] AS [id],
        ///  INSERTED.[created] AS [created],
        ///  INSERTED.[updated] AS [updated],
        ///  INSERTED.[batch_size] AS [batch_size],
        ///  INSERTED.[timeout] AS [timeout],
        ///  INSERTED.[clock_drift] AS [clock_drift],
        ///  INSERTED.[started] AS [started],
        ///  INSERTED.[completed] AS [completed],
        ///  INSERTED.[state] AS [state],
        ///  INSERTED.[error] AS [error]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryMarkJobAsReady {
            get {
                return ResourceManager.GetString("QueryMarkJobAsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///  [dipren].[jobs]
        ///SET
        ///  [updated] = @timestamp,
        ///  [started] = @timestamp,
        ///  [state] = @state
        ///OUTPUT
        ///  INSERTED.[id] AS [id],
        ///  INSERTED.[created] AS [created],
        ///  INSERTED.[updated] AS [updated],
        ///  INSERTED.[batch_size] AS [batch_size],
        ///  INSERTED.[timeout] AS [timeout],
        ///  INSERTED.[clock_drift] AS [clock_drift],
        ///  INSERTED.[started] AS [started],
        ///  INSERTED.[completed] AS [completed],
        ///  INSERTED.[state] AS [state],
        ///  INSERTED.[error] AS [error]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryMarkJobAsStarted {
            get {
                return ResourceManager.GetString("QueryMarkJobAsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///DECLARE @progress TABLE
        ///(
        ///  [id] UNIQUEIDENTIFIER,
        ///  [updated] DATETIME,
        ///  [position] TEXT NULL,
        ///  [processed] BIGINT,
        ///  [remaining] BIGINT,
        ///  [throughput] DOUBLE PRECISION
        ///);
        ///
        ///UPDATE
        ///  [dipren].[progress]
        ///SET
        ///  [updated] = @updated,
        ///  [position] = @position,
        ///  [processed] = @processed,
        ///  [remaining] = @remaining,
        ///  [throughput] = @throughput
        ///OUTPUT
        ///  INSERTED.[id],
        ///  INSERTED.[updated],
        ///  INSERTED.[position],
        ///  INSERTED.[processed],
        ///  INSERTED.[remaining],
        ///  IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryReportProgress {
            get {
                return ResourceManager.GetString("QueryReportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
        ///
        ///SELECT
        ///  [id] AS &quot;id&quot;,
        ///  [created] AS [created],
        ///  [updated] AS [updated],
        ///  [batch_size] AS [batch_size],
        ///  [timeout] AS [timeout],
        ///  [clock_drift] AS [clock_drift],
        ///  [started] AS [started],
        ///  [completed] AS [completed],
        ///  [state] AS [state],
        ///  [error] AS [error]
        ///FROM
        ///  [dipren].[jobs]
        ///WHERE
        ///  ([id] = @id);.
        /// </summary>
        internal static string QueryRetrieveJobById {
            get {
                return ResourceManager.GetString("QueryRetrieveJobById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///WITH &quot;partitions&quot; AS
        ///(
        ///  SELECT
        ///    t1.[id] AS [id],
        ///    t1.[job_id] AS [job_id],
        ///    t1.[created] AS [created],
        ///    t2.[updated] AS [updated],
        ///    t1.[owner] AS [owner],
        ///    t1.[acquired] AS [acquired],
        ///    t1.[first] AS [first],
        ///    t1.[last] AS [last],
        ///    t1.[is_inclusive] AS [is_inclusive],
        ///    t2.[position] AS [position],
        ///    t2.[processed] AS [processed],
        ///    t2.[remaining] AS [remaining],
        ///    t2.[throughput] AS [throughput],
        ///    t1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryRetrieveJobStatusReport {
            get {
                return ResourceManager.GetString("QueryRetrieveJobStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  t1.[id] AS [id],
        ///  t1.[job_id] AS [job_id],
        ///  t1.[created] AS [created],
        ///  t2.[updated] AS [updated],
        ///  t1.[owner] AS [owner],
        ///  t1.[first] AS [first],
        ///  t1.[last] AS [last],
        ///  t1.[is_inclusive] AS [is_inclusive],
        ///  t2.[position] AS [position],
        ///  t2.[processed] AS [processed],
        ///  t2.[remaining] AS [remaining],
        ///  t2.[throughput] AS [throughput],
        ///  t1.[is_completed] AS [is_completed],
        ///  t1.[split_requester] AS [split_requester]
        ///FROM
        ///  [dipren].[partitions] AS [t1]
        ///  INNER JOIN [dipren [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryRetrievePartitionById {
            get {
                return ResourceManager.GetString("QueryRetrievePartitionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///SELECT
        ///  1
        ///FROM
        ///  [dipren].[jobs] WITH (NOLOCK)
        ///WHERE
        ///  ([id] = @job_id);
        ///
        ///DECLARE @id UNIQUEIDENTIFIER =
        ///(
        ///  SELECT TOP 1
        ///    t1.[id]
        ///  FROM
        ///    [dipren].[partitions] AS t1 WITH (ROWLOCK, UPDLOCK, READPAST)
        ///    INNER JOIN [dipren].[progress] AS t2 WITH (NOLOCK) ON (t1.[id] = t2.[id])
        ///  WHERE
        ///    (t1.[job_id] = @job_id) AND
        ///    ((t1.[owner] IS NULL) OR (t2.[updated] &lt; @active)) AND
        ///    (t1.[is_completed] = 0)
        ///  ORDER BY
        ///    t2.[remaining] DESC
        ///);
        ///
        ///DECLARE @partiti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryTryAcquirePartition {
            get {
                return ResourceManager.GetString("QueryTryAcquirePartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///SELECT
        ///  1
        ///FROM
        ///  [dipren].[jobs] WITH (NOLOCK)
        ///WHERE
        ///  ([id] = @job_id);
        ///
        ///WITH [candidate] AS
        ///(
        ///  SELECT TOP 1
        ///    t1.[id]
        ///  FROM
        ///    [dipren].[partitions] AS t1 WITH (ROWLOCK, UPDLOCK, READPAST)
        ///    INNER JOIN [dipren].[progress] AS t2 WITH (NOLOCK) ON (t1.[id] = t2.[id])
        ///  WHERE
        ///    (t1.[job_id] = @job_id) AND
        ///    (t1.[owner] IS NOT NULL) AND
        ///    (t2.[updated] &gt;= @active) AND
        ///    (t1.[is_completed] = 0) AND
        ///    (t1.[split_requester] IS NULL)
        ///  ORDER BY
        ///    t2.[r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryTryRequestSplit {
            get {
                return ResourceManager.GetString("QueryTryRequestSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///UPDATE
        ///  [dipren].[partitions]
        ///SET
        ///  [last] = @last,
        ///  [is_inclusive] = @is_inclusive,
        ///  [split_requester] = @split_requester
        ///WHERE
        ///  ([id] = @partition_id) AND
        ///  ([owner] = @owner);
        ///
        ///UPDATE
        ///  [dipren].[progress]
        ///SET
        ///  [updated] = @updated,
        ///  [position] = @position,
        ///  [processed] = @processed,
        ///  [remaining] = @remaining,
        ///  [throughput] = @throughput
        ///FROM
        ///  [dipren].[progress] AS t1
        ///  INNER JOIN [dipren].[partitions] AS t2 ON (t1.[id] = t2.[id])
        ///WHERE
        ///  (t1.[id] =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryUpdateSplitPartition {
            get {
                return ResourceManager.GetString("QueryUpdateSplitPartition", resourceCulture);
            }
        }
    }
}
